# Generated by Django 6.0.2 on 2026-02-21 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_user_profiles_and_map_invoices(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('Core', 'UserProfile')
    Invoice = apps.get_model('Core', 'Invoice')

    index = 1
    existing = list(UserProfile.objects.all().order_by('id'))
    if existing:
        try:
            index = max(int(p.uid.replace('UID', '')) for p in existing if str(p.uid).startswith('UID')) + 1
        except ValueError:
            index = len(existing) + 1

    for user in User.objects.filter(is_staff=False, is_superuser=False).order_by('id'):
        profile = UserProfile.objects.filter(user_id=user.id).first()
        if profile:
            continue
        uid = f'UID{index:03d}'
        UserProfile.objects.create(user_id=user.id, uid=uid)
        index += 1

    for invoice in Invoice.objects.filter(customer__isnull=True):
        if not hasattr(invoice, 'customer_name'):
            continue
        username = (invoice.customer_name or '').strip()
        if not username:
            continue
        user = User.objects.filter(username=username).first()
        if user:
            invoice.customer_id = user.id
            invoice.save(update_fields=['customer'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['uid'],
            },
        ),
        migrations.RunPython(seed_user_profiles_and_map_invoices, noop),
        migrations.RemoveField(
            model_name='invoice',
            name='customer_name',
        ),
    ]
