# Generated by Django 6.0.2 on 2026-02-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_remove_invoice_customer_name_invoice_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='control_number',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
