# Generated by Django 6.0.2 on 2026-02-26 17:05

from django.db import migrations, models
from random import SystemRandom


def normalize_control_numbers(apps, schema_editor):
    Invoice = apps.get_model('Core', 'Invoice')
    rng = SystemRandom()
    used = set()
    all_existing = list(Invoice.objects.all().order_by('id'))

    def next_unique():
        while True:
            candidate = str(rng.randrange(0, 1_000_000_000)).zfill(9)
            if candidate not in used:
                used.add(candidate)
                return candidate

    for invoice in all_existing:
        value = invoice.control_number
        value = '' if value is None else str(value).strip()
        if len(value) == 9 and value.isdigit() and value not in used:
            used.add(value)
            if invoice.control_number != value:
                invoice.control_number = value
                invoice.save(update_fields=['control_number'])
        else:
            invoice.control_number = next_unique()
            invoice.save(update_fields=['control_number'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_invoice_control_number'),
    ]

    operations = [
        migrations.RunPython(normalize_control_numbers, noop),
        migrations.AlterField(
            model_name='invoice',
            name='control_number',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
    ]
